name: Sphinx build

on: 
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build HTML
      uses: ammaraskar/sphinx-action@7.0.0
      with:
        docs-folder: "./docs"

    
    - name: Upload static files as artifact
      id: deployment
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs/_build/html/

  # Deployment job
  deploy:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    # Set permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      if: github.ref == 'refs/heads/master'
      uses: actions/deploy-pages@v4

